# Generated by Django 4.1 on 2022-08-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='file_name',
            field=models.FileField(max_length=150, upload_to='csvs/'),
        ),
    ]
